Hotkey for dispatcher
Yousei9/Logistic-Train-Network pull request #234
Opened 2020-10-03 13:46 UTC by StephanSteinert

Added a hotkey for quickly enabling/disabling the dispatcher.

2020-10-03 15:33 UTC, Yousei9 requested changes
Disabling Dispatcher is common enough to warrant a shortcut?

Please use 2 whitespaces per indent for consistency.

2020-10-03 15:33 UTC, Yousei9 commented on locale/de/base.cfg
> +ltn-toggle-dispatcher=LTN-Dispatcher ein-/ausschalten.
Should be "LTN-Disponent ein-/ausschalten." for consistency

2020-10-03 16:24 UTC, Yousei9 commented
Should i credit your name from GitHub or the more recognized steinio?

2020-10-03 19:06 UTC, StephanSteinert commented
Steinio would be better i think.

2020-10-04 04:58 UTC, merged

2020-10-04 04:58 UTC, Yousei9 approved these changes